import './globals.css'
import { Inter } from 'next/font/google'
import ThemeWrapper from '@/src/shared/ThemeWrapper/ThemeWrapper'
import MainContentContainer from '@/src/shared/MainContentContainer/MainContentContainer'
import Nav from '@/src/shared/components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeWrapper>
          <header>
            <Nav />
          </header>
          <MainContentContainer>
            {children}
          </MainContentContainer>
        </ThemeWrapper>
      </body>
    </html>
  )
}
